url: https://localhost:4000
# baseurl:

# Site settings
title: rombolabs
email: rombolab@uw.edu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Projects
collections:
  projects :
    output : true
    permalink : /:collection/:path/

leader:
- name: Eric Rombokas
  pic: rombokas.png
  peek: rombokasGoggles.gif
  position: Investigator Supreme
  social:
    - title: link
      url: http://rombokas.com/eric/
    - title: linkedin
      url: https://www.linkedin.com/in/eric-rombokas-2589099/

# Team names, titles and social links
headshotsize: 200px
people:


- name: Astrini Sie
  pic: astrini.jpg
  peek: dank.jpg
  position: PhD Candidate - Electrical Engineering
  social:
    - title: envelope
      url: mailto:astrini@uw.edu
    - title: linkedin
      url: https://www.linkedin.com/in/astrinisie/

- name: David Boe
  pic: davidboe.jpg
  peek: dank.jpg
  position: Prosthetologist & Neurobiologist
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/david-boe-6b43b613b/

- name: David Caballero
  pic: dcaballe.jpg
  peek: dank.jpg
  position: PhD Candidate - Electrical Engineering
  social:
    - title: envelope
      url: mailto:dcabelle@uw.edu

- name: Gaurav Mukherjee
  pic: mgaurav.jpg
  peek: dank.jpg
  position: PhD Student - Mechanical Engineering
  social:
#    - title: envelope
#      url: mailto:mgaurav@uw.edu
    - title: linkedin
      url: https://www.linkedin.com/in/mukherjeegaurav/

- name: Lalit Palve
  pic: lalitp.jpg
  peek: dank.jpg
  position: Masters Candidate - Mechanical Engineering
  social:
#    - title: envelope
#      url: mailto:lalitp@uw.edu
    - title: linkedin
      url: https://www.linkedin.com/in/lalit-palve-a9a28654/

- name: Luke Johnson
  pic: lukej.jpg
  peek: dank.jpg
  position: Masters Candidate - Mechanical Engineering
  social:
#    - title: envelope
#      url: mailto:lukej11@uw.edu
    - title: linkedin
      url: https://www.linkedin.com/in/lukekjohnson/

- name: Nataliya Rokhmanova
  pic: nrokh.jpg
  peek: dank.jpg
  position: Masters Student - Mechanical Engineering
  social:
    - title: envelope
      url: mailto:nrokh@uw.edu
    - title: linkedin
      url: https://www.linkedin.com/in/rokhmanova/

- name: Pornthep Preechayasomboon
  pic: prnthp.jpg
  peek: dank.jpg
  position: Masters Student - Soft Robotics Engineering
  social:
    - title: envelope
      url: mailto:prnthp@uw.edu
    - title: linkedin
      url: https://www.linkedin.com/in/pornthep/
    - title: github
      url: https://prnthp.github.io

- name: Vijeth Rai
  pic: raiv.jpg
  peek: dank.jpg
  position: PhD Candidate - Electrical Engineering
  social:
    - title: envelope
      url: mailto:raiv@uw.edu




# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/rombolabs
  - title: github
    url: http://github.com/rombolabs

contactinfo:
  - line: rombolab@uw.edu
  - line: 206-764-2991

addresses:
  - address:
    - line: University of Washington
    - line: Seattle, WA 98105
  - address:
    - line: VA Puget Sound Health Care System
    - line: VA RR&D Center, MS 151
    - line: 1660 South Columbian Way
    - line: Seattle, WA 98105

# Build settings
markdown: kramdown
permalink: pretty
